spring:
  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver
  batch:
    initialize-schema: always
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: "UTC+1"
          lob:
            non_contextual_creation: true
        session-factory:
  data:
    rest:
      base-path: api
  h2:
    console:
      enabled: true



#server:
#  ssl:
#    key-store: 'classpath:keystore/repairman.jks'
#    key-store-type: JKS
#    key-password: password
#    key-alias: repairman
#    #trust-store: 'classpath:keystore/repairman.jks'
#    #trust-store-password: password
#    key-store-password: password
