spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:default
    username: sa
  batch:
    initialize-schema: always
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        session-factory:
  data:
    rest:
      base-path: api

name:
  default: nazwa
