spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  batch:
    initialize-schema: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        session-factory:
  data:
    rest:
      base-path: api
#security:
  #require-ssl: true
server:
  ssl:
    key-store: 'classpath:keystore/repairman.jks'
    key-store-type: JKS
    key-password: password
    key-alias: repairman
    #trust-store: 'classpath:keystore/repairman.jks'
    #trust-store-password: password
    key-store-password: password